// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYHjInf4HSfBGPxvt_deM3J5QnZN68zQ8',
    appId: '1:439440106789:web:9aa90dc4a2b2de560ba6cc',
    messagingSenderId: '439440106789',
    projectId: 'firstprojectdart',
    authDomain: 'firstprojectdart.firebaseapp.com',
    storageBucket: 'firstprojectdart.appspot.com',
    measurementId: 'G-ZWG4310R7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrxEeNWfus12h0Hyk7M6RTItPtT6jHP4g',
    appId: '1:439440106789:android:00c25c95489b75280ba6cc',
    messagingSenderId: '439440106789',
    projectId: 'firstprojectdart',
    storageBucket: 'firstprojectdart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvaeKYvcxDiuoSPQdh1AQ_kujOdrPAPNU',
    appId: '1:439440106789:ios:b1d710550b6ab54e0ba6cc',
    messagingSenderId: '439440106789',
    projectId: 'firstprojectdart',
    storageBucket: 'firstprojectdart.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYHjInf4HSfBGPxvt_deM3J5QnZN68zQ8',
    appId: '1:439440106789:web:5b0a621843b5b64e0ba6cc',
    messagingSenderId: '439440106789',
    projectId: 'firstprojectdart',
    authDomain: 'firstprojectdart.firebaseapp.com',
    storageBucket: 'firstprojectdart.appspot.com',
    measurementId: 'G-KC8GFDY9M2',
  );
}
